### ISSUE TITLE
第二次读条准备软件更新时失败

### ISSUE THREAD

**Issue by gatsbyzheng** [MrChium/Hackintosh-B460M-MORTAR-i5-10500-iGPU-UHD630#83]
平台为msib460m+i510500+铠侠rc10，表现为第二次安装读条走到一半，弹出“准备软件更新时失败”。而且这个现象很奇怪，我的电脑有三块硬盘，分别为西数sn500、铠侠rc10、三星970evo（sata）。安装在sata的固态里面可以正常安装，其他两块nvme的固态均表现为同样错误，如果有谁遇到过跪求解决方案。

**Comment by cxp863** [comment]
同rc10，cpu是10700。更新opencore 0.7.4以上 就OK了

**Comment by Gatsbyzheng** [comment]
> 同rc10，cpu是10700。更新opencore 0.7.4以上 就OK了

感谢您的回复，我使用的oc版本就是0.7.4，这个问题依旧存在。

**Comment by gatsbyzheng** [comment]
这个问题终结，内存条的问题导致的，我的内存条是16g*2的光威，换成了其他牌子的内存条，再也没有这个问题了
